# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0010_make_external_ids_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citation.Publication'),
        ),
    ]
