# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0011_note_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='pub_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditlog', to='citation.Publication'),
        ),
    ]
