# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-16 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0013_move_payload_to_pub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date this url was last verified')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date this url status was last modified on this system')),
                ('headers', models.TextField(blank=True, help_text='contains information about the url header')),
                ('type', models.TextField(choices=[('COMSES', 'CoMSES'), ('OPEN SOURCE', 'Open Source'), ('PLATFORM', 'Platform'), ('JOURNAL', 'Journal'), ('PERSONAL', 'Personal'), ('INVALID', 'Invalid'), ('OTHERS', 'Others')])),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('status_reason', models.TextField(blank=True, help_text='contains reason for the url success/failure')),
                ('system_generated', models.BooleanField(default=True)),
                ('publication', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_status', to='citation.Publication')),
            ],
        ),
    ]
