# Generated by Django 2.0.10 on 2019-01-15 19:17

import citation.fields
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('citation', '0014_add_url_status_logs_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('new_content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_applied', models.DateTimeField(null=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('model__in', ['author', 'container', 'platform', 'publication', 'sponsor']), ('app_label', 'citation')), on_delete=django.db.models.deletion.PROTECT, related_name='suggested_merge_set', to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggested_merge_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', citation.fields.NonEmptyTextField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOI')),
                ('title', models.TextField(blank=True, default='')),
                ('journal', models.TextField(blank=True, default='')),
                ('volume', models.CharField(blank=True, default='', max_length=255)),
                ('issue', models.CharField(blank=True, default='', max_length=255)),
                ('pages', models.CharField(blank=True, default='', max_length=255)),
                ('authors', models.CharField(blank=True, default='', max_length=300)),
                ('code_archive_url', models.URLField(blank=True, max_length=255)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citation.Submitter')),
            ],
        ),
        migrations.AlterField(
            model_name='auditcommand',
            name='creator',
            field=models.ForeignKey(help_text='The user who initiated this action, if any.', on_delete=django.db.models.deletion.PROTECT, related_name='citation_creator_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='pub_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auditlog', to='citation.Publication'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorcorrespondence',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondences', to='citation.AuthorCorrespondenceTemplate'),
        ),
        migrations.AlterField(
            model_name='invitationemailtemplate',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citation_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citation_added_note_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation_deleted_note_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citation_added_publication_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='assigned_curator',
            field=models.ForeignKey(blank=True, help_text='Currently assigned curator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation_assigned_publication_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='citation.Container'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='publications', through='citation.PublicationTags', to='citation.Tag'),
        ),
        migrations.AlterField(
            model_name='publicationplatforms',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_platforms', to='citation.Platform'),
        ),
        migrations.AlterField(
            model_name='urlstatuslog',
            name='publication',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='url_status', to='citation.Publication'),
        ),
    ]
