# Generated by Django 2.0.10 on 2019-01-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0015_add_suggested_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstatuslog',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
