# Generated by Django 2.0.10 on 2019-01-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0016_increase_url_status_log_max_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedmerge',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggested_merge_set', to='citation.Submitter'),
        ),
    ]
