# Generated by Django 2.0.10 on 2019-01-18 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citation', '0017_change_suggested_merge_creator_to_submitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeArchiveUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('category', models.CharField(choices=[(('Archived', ('comses', 'CoMSES'), ('figshare', 'FigShare')), ('Not Assigned', ('', 'Empty')))], default='', max_length=100)),
                ('status', models.CharField(choices=[(('available', 'Available'), ('unavailable', 'Unavailable'))], max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citation.Publication')),
            ],
        ),
    ]
