# Generated by Django 2.0.10 on 2019-01-18 22:00

from django.db import migrations


def annex_code_archive_urls(apps, schema_editor):
    Publication = apps.get_model('citation', 'Publication')
    CodeArchiveURL = apps.get_model('citation', 'CodeArchiveURL')

    code_archive_urls = []
    publications_with_urls = Publication.objects.exclude(code_archive_url='')
    for publication in publications_with_urls:
        code_archive_url = CodeArchiveURL(publication=publication,
                                          url=publication.code_archive_url,
                                          status='unavailable',
                                          creator=publication.added_by)
        code_archive_urls.append(code_archive_url)

    CodeArchiveURL.objects.bulk_create(code_archive_urls)


def combine_code_archive_urls(apps, schema_editor):
    CodeArchiveURL = apps.get_model('citation', 'CodeArchiveURL')

    code_archive_urls = CodeArchiveURL.objects.select_related('publication').order_by('id')
    for code_archive_url in code_archive_urls:
        publication = code_archive_url.publication
        publication.code_archive_url = code_archive_url.url
        publication.save()


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0018_codearchiveurl'),
    ]

    operations = [
        migrations.RunPython(code=annex_code_archive_urls, reverse_code=combine_code_archive_urls)
    ]
