# Generated by Django 2.0.10 on 2019-02-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0020_make_urlstatuslog_related_publication_and_add_codearchiveurl_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='codearchiveurl',
            name='system_overridable_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='codearchiveurl',
            name='category',
            field=models.CharField(choices=[('CoMSES', 'Archives / CoMSES'), ('Zenodo', 'Archives / Zenodo'), ('Dataverse', 'Archives / Dataverse'), ('Figshare', 'Archives / Figshare'), ('OSF', 'Archives / OSF'), ('GitHub', 'Repositories / GitHub'), ('SourceForge', 'Repositories / SourceForge'), ('BitBucket', 'Repositories / BitBucket'), ('GoogleCode', 'Repositories / GoogleCode'), ('Personal', 'Personal / DropBox'), ('ResearchGate', 'Personal / ResearchGate'), ('PersonalWebsite', 'Personal / PersonalWebsite'), ('Invalid', 'Invalid'), ('Unknown', 'Unknown'), ('', 'Empty')], default='', max_length=100),
        ),
    ]
