# Generated by Django 2.0.10 on 2019-02-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0025_migrate_category_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codearchiveurl',
            name='category',
        ),
        migrations.RenameField(
            model_name='codearchiveurl',
            old_name='category_model',
            new_name='category'
        ),
        migrations.AlterField(
            model_name='codearchiveurl',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_archive_urls',
                                    to='citation.CodeArchiveUrlCategory'),
        ),
    ]
