# Generated by Django 2.1.7 on 2019-03-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0026_replace_string_category_with_foreign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCorrespondenceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_responded', models.DateTimeField(null=True)),
                ('contact_author_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('purpose', models.TextField(choices=[('NOT_IN_ARCHIVE', 'Code available but not in archive'), ('IN_ARCHIVE', 'Code available in archive'), ('NOT_AVAILABLE', 'Code not available')], max_length=50)),
                ('content', models.TextField(max_length=6000)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citation.Publication')),
            ],
        ),
        migrations.RemoveField(
            model_name='authorcorrespondence',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorcorrespondence',
            name='template',
        ),
        migrations.DeleteModel(
            name='AuthorCorrespondence',
        ),
        migrations.DeleteModel(
            name='AuthorCorrespondenceTemplate',
        ),
    ]
