# Generated by Django 2.2 on 2019-04-30 22:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0028_email_delivery_status_choices'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='codearchiveurl',
            managers=[
                ('api', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='codearchiveurl',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True if this Archive URL is not defunct, i.e., has been replaced.'),
        ),
        migrations.AddField(
            model_name='codearchiveurl',
            name='notes',
            field=models.TextField(blank=True, help_text='Remarks on this URL from the author or curator'),
        ),
        migrations.AlterField(
            model_name='codearchiveurl',
            name='status',
            field=models.CharField(choices=[('available', 'Available: Codebase is currently openly accessible at the specified URL'), ('restricted', 'Restricted: Specified URL is locked behind authentication or paywall'), ('unavailable', 'Unavailable: No URL available or URL does not resolve')], max_length=100),
        ),
        migrations.AlterField(
            model_name='codearchiveurl',
            name='system_overridable_category',
            field=models.BooleanField(default=True, help_text="Signifies that this URL's category can be overridden (i.e., not user entered)."),
        ),
        migrations.AlterField(
            model_name='suggestedmerge',
            name='date_applied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
