# Generated by Django 2.2.4 on 2019-08-06 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0030_remove_model_documentation_source_code_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorcorrespondencelog',
            name='author_feedback',
            field=models.TextField(help_text='Correspondence / feedback / corrections to this metadata record'),
        ),
        migrations.AlterField(
            model_name='authorcorrespondencelog',
            name='status',
            field=models.CharField(choices=[('NOT_AVAILABLE', 'Code not available'), ('NOT_IN_ARCHIVE', 'Code has an accessible URL but not in a trusted digital repository'), ('ARCHIVED', 'Code is archived in a trusted digital repository')], max_length=64),
        ),
        migrations.AlterField(
            model_name='codearchiveurlpattern',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patterns', to='citation.CodeArchiveUrlCategory'),
        ),
    ]
