# Generated by Django 5.2.12 on 2026-04-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0033_publicationauthors_corresponding_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='payload',
            field=models.JSONField(blank=True, help_text='A JSON dictionary containing modified fields, if any, for the given publication', null=True),
        ),
        migrations.AlterField(
            model_name='authorcorrespondencelog',
            name='author_feedback',
            field=models.TextField(blank=True, help_text='Correspondence / feedback / corrections to this metadata record'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citations',
            field=models.ManyToManyField(related_name='referenced_by', through='citation.PublicationCitations', through_fields=('publication', 'citation'), to='citation.publication'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='suggestedmerge',
            name='new_content',
            field=models.JSONField(),
        ),
    ]
