name: CoMSES Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: build containers
      run: ./build.sh
    - name: Run Django tests
      run: |
        docker compose run --rm test
